# Generated by Django 4.2.23 on 2025-06-24 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='feature_priority',
            field=models.IntegerField(),
        ),
    ]
