# Generated by Django 4.2.23 on 2025-06-24 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_alter_vendor_feature_priority'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='products',
        ),
        migrations.AddField(
            model_name='product',
            name='vendor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='market.vendor'),
            preserve_default=False,
        ),
    ]
