# Generated by Django 4.2.23 on 2025-06-24 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_consumer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consumer',
            name='password',
        ),
        migrations.RemoveField(
            model_name='consumer',
            name='username',
        ),
    ]
