# Generated by Django 4.2.23 on 2025-10-16 00:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0005_remove_consumer_password_remove_consumer_username'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-is_featured', 'name']},
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('vegetables', 'Vegetables'), ('fruits', 'Fruits'), ('dairy', 'Dairy'), ('meat', 'Meat'), ('grains', 'Grains'), ('herbs', 'Herbs'), ('prepared', 'Prepared Foods'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Featured products appear at top of vendor page'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='service_area',
            field=models.TextField(blank=True, help_text='Geographic areas where vendor provides service', null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='ships_goods',
            field=models.BooleanField(default=False, help_text='Whether vendor ships products'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='story_mission',
            field=models.TextField(blank=True, help_text="Vendor's story and mission", null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='feature_priority',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumer_name', models.CharField(help_text='Name of the reviewer', max_length=100)),
                ('rating', models.IntegerField(choices=[(1, '1 Star'), (2, '2 Stars'), (3, '3 Stars'), (4, '4 Stars'), (5, '5 Stars')])),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='market.vendor')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
