# Generated by Django 4.1 on 2025-06-14 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_vendor_description_vendor_vendortype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='state',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
